```{r forestuni, fig.cap="Crude Forestplot - association between systolic blood pressure/treatment and CVD/First HFH", cache=cacheon}

n <- pdata %>%
  group_by(sysbp_suptreat) %>%
  count(sos_out_deathcvhosphf) %>%
  mutate(
    tot = sum(n),
    ntot = paste0(n, "/", tot)
  ) %>%
  ungroup() %>%
  filter(sos_out_deathcvhosphf == "Yes")

# crude

moduni <- coxph(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~ sysbp_suptreat, data = pdata)

modunis <- summary(moduni)

# labs <- levels(pdata$sysbp_suptreat)

labs1 <- rep(c("SBP \u2265140 mmHg", "SBP 120-139 mmHg", "SBP 100-119 mmHg", "SBP 90-99 mmHg", "SBP <90 mmHg"), each = 4)

labs2 <- rep(c("ST 100%", "ST 51-99%", "ST 50%", "ST <50%"), 5)

loghr <- c(0, modunis$coefficients[, 1])

loglci <- c(0, log(modunis$conf.int[, 3]))

loguci <- c(0, log(modunis$conf.int[, 4]))

hrci <- paste0(
  dF(exp(loghr), 1), " (",
  dF(exp(loglci), 1), "-",
  dF(exp(loguci), 1), ")"
)

hrci[1] <- "ref"

outforest <- data.frame(cbind(labs1, labs2, loghr, loglci, loguci, hrci, ntot = n %>% pull(ntot)))

outforest <- rbind(
  outforest[1:4, ], rep(NA, 6),
  outforest[5:8, ], rep(NA, 6),
  outforest[9:12, ], rep(NA, 6),
  outforest[13:16, ], rep(NA, 6),
  outforest[17:20, ]
)

outforest <- outforest %>% arrange(desc(row_number()))

nf <- nrow(outforest)

# exp(min(loglci, na.rm = T))
# exp(max(loguci, na.rm = T))
# c(bottom, left, top, right)

par(mar = c(3, 21, 1, 2) + 0.2)

cextext <- 0.9

plot(outforest$loghr, 1:nf,
  cex = 1.2,
  xlim = c(
    log(.9),
    log(5.5)
  ),
  xlab = "",
  ylim = c(1, nf + 1.4),
  axes = FALSE,
  ylab = NA,
  main = NA,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)

for (i in 1:nf) {
  lines(c(outforest$loglci[i], outforest$loguci[i]), c(i, i),
    col = global_kicols[1], cex = 2
  )
}

matplot(c(log(1), log(1)), c(-1, nf + 1), type = "l", lwd = 1, lty = 1, add = TRUE, col = 1)
atmy <- seq(0.9, 5.5, 0.1)
atmy2 <- atmy
atmy2[!dF(atmy, 1) %in% dF(c(1, 2, 3, 4, 5), 1)] <- NA
axis(1,
  cex.axis = cextext, at = log(atmy),
  gap.axis = -100000,
  labels = atmy2
)
axis(1,
  cex.axis = cextext,
  at = (log(5.5) - abs(log(0.9))) / 2,
  labels = "Crude HR (95% CI)",
  line = 1,
  tick = FALSE
)
axis(2,
  at = seq(2.5, nf, 5),
  labels = unique(rev(labs1)),
  cex.axis = cextext, tick = FALSE, las = 2, line = 20, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1, nf + 2),
  labels = c(outforest$labs2, "dose", "HF treatment"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 12.2, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1),
  labels = c(outforest$ntot, "n event/N"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 7.3, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1, nf + 2), labels = c(outforest$hrci, "HR (95% CI)", "Crude"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 1, hadj = 0.5
)
```

```{r forestadjnt, fig.cap="Forestplot adjusted for NT-proBNP- association between systolic blood pressure/treatment and CVD/First HFH", cache=cacheon}

n <- pdata %>%
  group_by(sysbp_suptreat) %>%
  count(sos_out_deathcvhosphf) %>%
  mutate(
    tot = sum(n),
    ntot = paste0(n, "/", tot)
  ) %>%
  ungroup() %>%
  filter(sos_out_deathcvhosphf == "Yes")

# adjusted
modadj <- with(impdata, coxph(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~
sysbp_suptreat + ns(shf_ntpropbnp, 3)))

# df the number of events minus the regression coefficients.
# There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
modadjs <- summary(pool(modadj,
  dfcom = (modadj$analyses[[1]]$nevent - length(modadj$analyses[[1]]$coefficients))
))

# labs <- levels(pdata$sysbp_suptreat)

labs1 <- rep(c("SBP \u2265140 mmHg", "SBP 120-139 mmHg", "SBP 100-119 mmHg", "SBP 90-99 mmHg", "SBP <90 mmHg"), each = 4)

labs2 <- rep(c("ST 100%", "ST 51-99%", "ST 50%", "ST <50%"), 5)

loghr <- c(0, modadjs$estimate)

loglci <- c(0, modadjs$estimate - global_z05 * modadjs$std.error)

loguci <- c(0, modadjs$estimate + global_z05 * modadjs$std.error)

hrci <- paste0(
  dF(exp(loghr), 1), " (",
  dF(exp(loglci), 1), "-",
  dF(exp(loguci), 1), ")"
)

hrci[1] <- "ref"

outforest <- data.frame(cbind(labs1, labs2, loghr, loglci, loguci, hrci, ntot = n %>% pull(ntot)))

outforest <- rbind(
  outforest[1:4, ], rep(NA, 6),
  outforest[5:8, ], rep(NA, 6),
  outforest[9:12, ], rep(NA, 6),
  outforest[13:16, ], rep(NA, 6),
  outforest[17:20, ]
)

outforest <- outforest %>% arrange(desc(row_number()))

nf <- nrow(outforest)

# exp(min(loglci, na.rm = T))
# exp(max(loguci, na.rm = T))
# c(bottom, left, top, right)

par(mar = c(3, 21, 1, 2) + 0.2)

cextext <- 0.9

plot(outforest$loghr, 1:nf,
  cex = 1.2,
  xlim = c(
    log(.9),
    log(4.0)
  ),
  xlab = "",
  ylim = c(1, nf + 1.4),
  axes = FALSE,
  ylab = NA,
  main = NA,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)

for (i in 1:nf) {
  lines(c(outforest$loglci[i], outforest$loguci[i]), c(i, i),
    col = global_kicols[1], cex = 2
  )
}

matplot(c(log(1), log(1)), c(-1, nf + 1), type = "l", lwd = 1, lty = 1, add = TRUE, col = 1)
atmy <- seq(0.9, 4, 0.1)
atmy2 <- atmy
atmy2[!dF(atmy, 1) %in% dF(c(1, 2, 3, 4), 1)] <- NA
axis(1,
  cex.axis = cextext, at = log(atmy),
  gap.axis = -10000000,
  labels = atmy2
)
axis(1,
  cex.axis = cextext,
  at = (log(4) - abs(log(0.9))) / 2,
  labels = "Adjusted NT-proBNP HR (95% CI)",
  line = 1,
  tick = FALSE
)
axis(2,
  at = seq(2.5, nf, 5),
  labels = unique(rev(labs1)),
  cex.axis = cextext, tick = FALSE, las = 2, line = 20, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1, nf + 2),
  labels = c(outforest$labs2, "dose", "HF treatment"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 12.2, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1),
  labels = c(outforest$ntot, "n event/N"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 7.3, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1, nf + 2), labels = c(outforest$hrci, "HR (95% CI)", "Adjusted NT-proBNP"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 1, hadj = 0.5
)
```

```{r forestsyncope, fig.cap="Crude Forestplot - association between systolic blood pressure/treatment and syncope", cache=cacheon}

n <- pdata %>%
  group_by(sysbp_suptreat) %>%
  count(sos_out_hospsyncope) %>%
  mutate(
    tot = sum(n),
    ntot = paste0(n, "/", tot)
  ) %>%
  ungroup() %>%
  filter(sos_out_hospsyncope == "Yes")


# crude

moduni <- coxph(Surv(sos_outtime_hospsyncope, sos_out_hospsyncope == "Yes") ~ sysbp_suptreat, data = pdata)
modunis <- summary(moduni)

minx <- 0.25
maxx <- 5.2

# labs <- levels(pdata$sysbp_suptreat)

labs1 <- rep(c("SBP \u2265140 mmHg", "SBP 120-139 mmHg", "SBP 100-119 mmHg", "SBP 90-99 mmHg", "SBP <90 mmHg"), each = 4)

labs2 <- rep(c("ST 100%", "ST 51-99%", "ST 50%", "ST <50%"), 5)

loghr <- c(0, modunis$coefficients[, 1])

loglci <- c(0, log(modunis$conf.int[, 3]))

loguci <- c(0, log(modunis$conf.int[, 4]))

hrci <- paste0(
  dF(exp(loghr), 1), " (",
  dF(exp(loglci), 1), "-",
  dF(exp(loguci), 1), ")"
)

hrci[1] <- "ref"

outforest <- data.frame(cbind(labs1, labs2, loghr, loglci, loguci, hrci, ntot = n %>% pull(ntot)))

outforest <- rbind(
  outforest[1:4, ], rep(NA, 6),
  outforest[5:8, ], rep(NA, 6),
  outforest[9:12, ], rep(NA, 6),
  outforest[13:16, ], rep(NA, 6),
  outforest[17:20, ]
)

outforest <- outforest %>% arrange(desc(row_number()))

nf <- nrow(outforest)

# exp(min(loglci, na.rm = T))
# exp(max(loguci, na.rm = T))
# c(bottom, left, top, right)

par(mar = c(3, 21, 1, 2) + 0.2)

cextext <- 0.9

plot(outforest$loghr, 1:nf,
  cex = 1.2,
  xlim = c(
    log(minx),
    log(maxx)
  ),
  xlab = "",
  ylim = c(1, nf + 1.4),
  axes = FALSE,
  ylab = NA,
  main = NA,
  type = "p",
  pch = 22,
  bg = global_kicols[1],
  col = global_kicols[1]
)

for (i in 1:nf) {
  lines(c(outforest$loglci[i], outforest$loguci[i]), c(i, i),
    col = global_kicols[1], cex = 2
  )
}

matplot(c(log(1), log(1)), c(-1, nf + 1), type = "l", lwd = 1, lty = 1, add = TRUE, col = 1)
atmy <- c(minx, seq(0.3, maxx, 0.1))
atmy2 <- atmy
atmy2[!dF(atmy, 1) %in% dF(c(0.25, 0.5, 1, 2, 3, 4, 5), 1)] <- NA
axis(1,
  cex.axis = cextext, at = log(atmy),
  gap.axis = -10000000,
  labels = atmy2
)
axis(1,
  cex.axis = cextext,
  at = (log(maxx) - abs(log(minx))) / 2,
  labels = "Crude HR (95% CI)",
  line = 1,
  tick = FALSE
)
axis(2,
  at = seq(2.5, nf, 5),
  labels = unique(rev(labs1)),
  cex.axis = cextext, tick = FALSE, las = 2, line = 20, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1, nf + 2),
  labels = c(outforest$labs2, "dose", "HF treatment"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 12.2, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1),
  labels = c(outforest$ntot, "n event/N"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 7.3, hadj = 0
)

axis(2,
  at = c(1:nf, nf + 1, nf + 2), labels = c(outforest$hrci, "HR (95% CI)", "Crude"),
  cex.axis = cextext, tick = FALSE, las = 2, line = 1, hadj = 0.5
)
```
