```{r kmfunc, cache=cacheon}
kmfunc <- function(subsetmy, ylabmy = "CVD/first HF hospitalisation (%)") {
  fit <- survfit(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~ shf_bpsys_cat,
    data = pdata, subset = subsetmy
  )
  ggsurvplot(fit,
    data = pdata, censor = FALSE, surv.scale = "percent", xscale = 365.25,
    break.x.by = c(365.25), xlim = c(0, 365.25 * 3),
    ylab = ylabmy, xlab = "Years",
    risk.table = FALSE,
    conf.int = FALSE, palette = global_kicols,
    # risk.table.height = 0.25,
    tables.theme = theme_cleantable(),
    axes.offset = FALSE,
    fontsize = 4,
    legend.labs = paste("SBP", c("<90", "90-99", "100-119", "120-139", "140-")),
    legend.title = "",
    legend = c(0.85, 0.9)
  )
}
```

```{r kmst1, fig.cap="Kaplan-Meier CVD/First HFH - Supremum treatment dose <50%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$supremumdose_cat == "<50%")
```

```{r kmst2, fig.cap="Kaplan-Meier CVD/First HFH - Supremum treatment dose 50%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$supremumdose_cat == "50%")
```

```{r kmst3, fig.cap="Kaplan-Meier CVD/First HFH - Supremum treatment dose 51-99%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$supremumdose_cat == "51-99%")
```

```{r kmst4, fig.cap="Kaplan-Meier CVD/First HFH - Supremum treatment dose 100%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$supremumdose_cat == "100%")
```

```{r kmras1, fig.cap="Kaplan-Meier CVD/First HFH - No ras", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_rasdosemax_cat == "No")
```

```{r kmras2, fig.cap="Kaplan-Meier CVD/First HFH - Ras dose <50%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_rasdosemax_cat == "<50%")
```

```{r kmras3, fig.cap="Kaplan-Meier CVD/First HFH - Ras dose >=50%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_rasdosemax_cat == ">=50%")
```

```{r kmbbl1, fig.cap="Kaplan-Meier CVD/First HFH - No Bbl", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_bbldosemax_cat == "No")
```

```{r kmbbl2, fig.cap="Kaplan-Meier CVD/First HFH - Bbl dose <50%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_bbldosemax_cat == "<50%")
```

```{r kmbbl3, fig.cap="Kaplan-Meier CVD/First HFH - Bbl dose >=50%", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_bbldosemax_cat == ">=50%")
```

```{r kmmra1, fig.cap="Kaplan-Meier CVD/First HFH - No MRA", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_mradosemax_cat == "No")
```

```{r kmmra2, fig.cap="Kaplan-Meier CVD/First HFH - MRA", cache=cacheon, dependson="kmfunc"}
kmfunc(subsetmy = pdata$shf_mradosemax_cat == "Yes")
```
