```{r shapeofassquint"}

quint_sbp <- pdata %>% summarise(
  p25 = quantile(shf_bpsys, p = 0.25),
  p33 = quantile(shf_bpsys, p = 0.33),
  p50 = quantile(shf_bpsys, p = 0.5),
  p66 = quantile(shf_bpsys, p = 0.66),
  p75 = quantile(shf_bpsys, p = 0.75)
)

quint_sbp
```

```{r shapeofasscvd1hfh2, fig.cap="Shape of association between SBP and CVD/First HFH"}

# from https://cran.r-project.org/web/packages/survival/vignettes/splines.pdf
mod <- coxph(Surv(sos_outtime_hosphf, sos_out_deathcvhosphf == "Yes") ~ ns(shf_bpsys, df = 5),
  data = pdata
)
ptemp <- termplot(mod, se = TRUE, plot = FALSE)
bpsysterm <- ptemp$shf_bpsys
center <- with(bpsysterm, y[x == quint_sbp$p50])
ytemp <- bpsysterm$y + outer(bpsysterm$se, c(0, -global_z05, global_z05), "*")

matplot(bpsysterm$x,
  exp(ytemp - center),
  log = "y",
  type = "l",
  lwd = 2,
  lty = c(1, 2, 2),
  col = c(global_kicols[1], global_kicols[4], global_kicols[4]),
  xlim = c(80, 180),
  ylim = c(.8, 3),
  xlab = "Systolic blood pressure",
  ylab = "Hazard Ratio"
)
```
